server:
  port: 8085

spring:
  application:
    name: academy-spring-2Gateway
  datasource:
    url: jdbc:postgresql://localhost:5432/academy_elite_security
    username: postgres
    password: Lemuel05
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: DOCENTI
              uri: http://localhost:8080
              predicates:
                - Path=/docenti/**
            - id: DISCENTI
              uri: http://localhost:8080
              predicates:
                - Path=/discenti/**
            - id: CORSI
              uri: http://localhost:8081
              predicates:
                - Path=/corsi/**